spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ECARE-APPOINTMENT-SERVICE
          uri: lb://ECARE-APPOINTMENT-SERVICE
          predicates:
            - Path=/api/home/**
    discovery:
      enabled: true
    config:
      uri: http://localhost:8080
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost