spring.application.name: api-gateway
spring.config.import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
logging.level.com.etisalat.apigateway.client.WsoClient: DEBUG
allowed:
  origins: true

spring:
  cloud:
    gateway:
      routes:
        - id: ecare-appointment-service
          uri: lb://ecare-appointment-service
          predicates:
            - Path=/api/ecare/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
    discovery:
      enabled: true
    config:
      uri: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost


jwt:
  secret: ephI80bgH88cCS0nAdUEexTZgaIa