spring.application.name: api-gateway
spring.config.import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
spring:
  cloud:
    gateway:
      routes:
        - id: ecare-appointment-service
          uri: lb://ecare-appointment-service
          predicates:
            - Path=/api/ecare/**
    discovery:
      enabled: true
    config:
      uri: http://localhost:8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost